name: Test pyglider
on: [push, pull_request]
jobs:
  test-gliders:
    name: pyglider (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9", "3.10", "3.11"]
    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Micromamba
      uses: mamba-org/provision-with-micromamba@v16
      with:
        environment-file: tests/environment.yml

    - name: Python ${{ matrix.python-version }}
      run: >
        micromamba activate pyglider-test
        && python -m pip install . 

    - name: Tests
      run: >
        micromamba activate TEST
        &&  pytest --cov --cov-report xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
