name: Test pyglider
on: [push, pull_request]
jobs:
  test-gliders:
    name: pyglider (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Micromamba
        uses: mamba-org/provision-with-micromamba@v16
        with:
          environment-file: tests/environment.yml

      - name: Python ${{ matrix.python-version }}
        run: >
          micromamba activate pyglider-test
          && python -m pip install . 
      - name: Conda info
        shell: bash -l {0}
        run: conda info; conda list
      - name: install pyglider source
        shell: bash -l {0}
        run: which pip; pip install -e .
      - name: Process seaexplorer
        shell: bash -l {0}
        run: which python; cd tests/example-data/example-seaexplorer; make clean-all; python process_deploymentRealTime.py
      - name: Process slocum
        shell: bash -l {0}
        run: which python; cd tests/example-data/example-slocum; make clean-all; python process_deploymentRealTime.py
      - name: Process seaexplorer-legato-flntu-arod-ad2cp
        shell: bash -l {0}
        run: which python; cd tests/example-data/example-seaexplorer-legato-flntu-arod-ad2cp; make clean-all; python process_deploymentRealTime.py
      - name: Run tests
        shell: bash -l {0}
        run: which python; pytest --cov --cov-report xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
